name: Get Salt Versions
author: dafyddj
description: Return a list of currently supported Salt versions
outputs:
  salt-latest:
    description: The latest currently supported Salt version
    value: ${{ steps.get-salt-versions.outputs.salt-latest }}
  salt-versions:
    description: A list of currently supported Salt versions
    value: ${{ steps.get-salt-versions.outputs.salt-versions }}
runs:
  using: composite
  steps:
    - id: get-salt-versions
      shell: bash
      run: |
        VERSIONS='["3004.2", "3005.3", "3006.3"]'
        echo "salt-versions=$VERSIONS" >> $GITHUB_OUTPUT
        LATEST=$(echo "$VERSIONS" | jq -r '. | max_by( split(".")|map(tonumber) )')
        echo "salt-latest=$LATEST" >> $GITHUB_OUTPUT
