---
name: Main
on: [push, pull_request]

jobs:
  pre-commit:
    name: Run `pre-commit`
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-tags depName=python/cpython
      PYTHON_VERSION: 3.12.6
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  gsv:
    name: Get Salt versions
    runs-on: ubuntu-latest
    outputs:
      salt-versions: ${{ steps.get-salt-versions.outputs.salt-versions }}
      salt-versions-els: ${{ steps.get-salt-versions.outputs.salt-versions-els }}
      salt-versions-rc: ${{ steps.get-salt-versions.outputs.salt-versions-rc }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - id: get-salt-versions
        name: Run this action
        uses: ./
      - run: |
          echo "::notice ::Latest Salt version: ${{ steps.get-salt-versions.outputs.salt-latest }}"
          echo "::notice ::Supported Salt versions: ${{ steps.get-salt-versions.outputs.salt-versions }}"
          echo "::notice ::Salt versions on extended life support: ${{ steps.get-salt-versions.outputs.salt-versions-els }}"
          echo "::notice ::Salt release candidate versions: ${{ steps.get-salt-versions.outputs.salt-versions-rc }}"
  show-salt-versions:
    name: Show Salt versions
    needs: gsv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - ${{ fromJSON(needs.gsv.outputs.salt-versions-els) }}
          - ${{ fromJSON(needs.gsv.outputs.salt-versions) }}
          - ${{ fromJSON(needs.gsv.outputs.salt-versions-rc) }}
    steps:
      - run: |
          echo "::notice ::Salt version: $SALT_VERSION"
        env:
          SALT_VERSION: ${{ matrix.version }}
  release:
    name: Release
    needs:
      - pre-commit
      - show-salt-versions
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run `semantic-release`
        uses: codfish/semantic-release-action@9a999e0cdb207de2c9d9d4276860435727818989 # v3.4.1
        id: sem-rel
        with:
          branches: |
            ["main"]
          plugins: |
            [ "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/github"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update branch for major version
        if: steps.sem-rel.outputs.new-release-published == 'true'
        run: git push
             https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
             HEAD:refs/heads/v${{steps.sem-rel.outputs.release-major}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
